spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:regions
    driverClassName: org.h2.Driver
    username: h2
    password: h2
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 9001
